"use client";

import { createContext, FormEvent, useContext, useEffect, useMemo, useState } from "react";
import {
  getEvents,
  getMemberships,
  getProducers,
  getProducts,
  createEventReservation,
  type EventRecord,
  type MembershipRecord,
  type ProducerRecord,
  type ProductRecord,
} from "./services/clubData";

type Product = { slug:string; name:string; category:string; maker:string; price:number; member:number; image:string; tag?:string; stock?:string; region?:string; process?:string; notes?:string };
type Event = { id:string; slug:string; name:string; type:string; date:string; time:string; price:number; member:number; seats:number; image:string; featured?:boolean };
type Producer = { slug:string; name:string; region:string; story:string; image:string };
type Plan = { name:string; price:number; kicker:string; features:string[]; popular?:boolean };

const WA="573001234567";
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
const whatsapp=(message:string)=>`https://wa.me/${WA}?text=${encodeURIComponent(message)}`;
const images={
  huila:"https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?auto=format&fit=crop&w=1200&q=85",
  narino:"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=85",
  sierra:"https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1000&q=85",
  v60:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=85",
  press:"https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1000&q=85",
  grinder:"https://images.unsplash.com/photo-1572119865084-43c285814d63?auto=format&fit=crop&w=1000&q=85",
  kit:"https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1000&q=85",
  filters:"https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=1000&q=85",
  event:"https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=85",
  event2:"https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&w=1200&q=85",
  venue:"https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1500&q=85"
};

const products:Product[]=[
 {slug:"huila-lavado",name:"Huila Lavado",category:"Café del mes",maker:"Finca El Horizonte",price:56000,member:48000,image:images.huila,tag:"Café del mes",stock:"Disponible",region:"Pitalito, Huila",process:"Lavado",notes:"Panela · mandarina · cacao"},
 {slug:"narino-natural",name:"Nariño Natural",category:"Cafés colombianos",maker:"Tostadores del Sur",price:52000,member:46000,image:images.narino,stock:"Disponible",region:"Buesaco, Nariño",process:"Natural",notes:"Frutos rojos · miel · chocolate"},
 {slug:"sierra-organico",name:"Sierra Nevada Orgánico",category:"Cafés colombianos",maker:"Café Sierra Clara",price:49000,member:43000,image:images.sierra,tag:"Orgánico",stock:"Bajo inventario",region:"Sierra Nevada",process:"Lavado",notes:"Caramelo · nuez · ciruela"},
 {slug:"v60-ceramico",name:"V60 Cerámico",category:"Métodos",maker:"Club del Café",price:85000,member:76000,image:images.v60,stock:"Disponible"},
 {slug:"prensa-francesa",name:"Prensa Francesa",category:"Métodos",maker:"Bodum",price:98000,member:88000,image:images.press,stock:"Disponible"},
 {slug:"molino-manual",name:"Molino Manual",category:"Accesorios",maker:"Club del Café",price:135000,member:120000,image:images.grinder,tag:"Favorito",stock:"Disponible"},
 {slug:"kit-inicio-filtrado",name:"Kit de Inicio Filtrado",category:"Kits",maker:"Club del Café",price:189000,member:169000,image:images.kit,stock:"Disponible"},
 {slug:"filtros-papel",name:"Filtros de Papel x100",category:"Accesorios",maker:"Hario",price:32000,member:28000,image:images.filters,stock:"Disponible"}
];
const events:Event[]=[
 {id:"mock-cata",slug:"cata-cafe-mes",name:"Cata del Café del Mes",type:"Cata",date:"22 AGO",time:"5:30 p. m.",price:45000,member:0,seats:8,image:images.event,featured:true},
 {id:"mock-metodos",slug:"metodos-casa",name:"Taller de Métodos en Casa",type:"Taller",date:"29 AGO",time:"10:00 a. m.",price:68000,member:52000,seats:6,image:images.event2},
 {id:"mock-maridaje",slug:"maridaje-postre",name:"Maridaje Café & Postre",type:"Maridaje",date:"05 SEP",time:"6:30 p. m.",price:75000,member:59000,seats:4,image:images.huila},
 {id:"mock-productor",slug:"productor-invitado",name:"Charla con Productor Invitado",type:"Charla",date:"12 SEP",time:"5:00 p. m.",price:25000,member:0,seats:16,image:images.sierra},
 {id:"mock-encuentro",slug:"encuentro-club",name:"Encuentro Gratuito del Club",type:"Gratuito",date:"20 SEP",time:"4:00 p. m.",price:0,member:0,seats:20,image:images.venue}
];
const producers:Producer[]=[
 {slug:"sierra-clara",name:"Café Sierra Clara",region:"Sierra Nevada",story:"Café cultivado entre bosque nativo, con prácticas regenerativas y cosecha manual.",image:images.sierra},
 {slug:"finca-horizonte",name:"Finca El Horizonte",region:"Huila",story:"Tres generaciones dedicadas a cafés dulces, limpios y profundamente colombianos.",image:images.huila},
 {slug:"tostadores-sur",name:"Tostadores del Sur",region:"Nariño",story:"Un colectivo que conecta pequeños lotes de altura con tostiones precisas y transparentes.",image:images.narino}
];
const plans:Plan[]=[
 {name:"Explorador",price:45000,kicker:"Empieza a vivir el Club",features:["Descuentos seleccionados","Acceso anticipado","Eventos gratuitos","Beneficios en sede"]},
 {name:"Catador",price:95000,kicker:"Descubre un café cada mes",features:["1 bolsa mensual","1 bebida mensual","1 cata grupal","Descuento en marketplace"],popular:true},
 {name:"Ritual",price:160000,kicker:"La experiencia completa",features:["1 bolsa premium","2 bebidas mensuales","1 experiencia incluida","Prioridad de reservas"]}
];

type ClubData = { products:Product[]; events:Event[]; producers:Producer[]; plans:Plan[] };
const ClubDataContext=createContext<ClubData>({products,events,producers,plans});
const useClubData=()=>useContext(ClubDataContext);

const text=(value:unknown,fallback:string)=>typeof value==="string"&&value.trim()?value:fallback;
const numeric=(value:unknown,fallback:number)=>typeof value==="number"&&Number.isFinite(value)?value:fallback;
const monthNames=["ENE","FEB","MAR","ABR","MAY","JUN","JUL","AGO","SEP","OCT","NOV","DIC"];
function eventDate(value:unknown,fallback:string){if(typeof value!=="string")return fallback;const parts=value.split("-");return parts.length===3?`${parts[2]} ${monthNames[Number(parts[1])-1]||""}`:fallback}
function eventTime(value:unknown,fallback:string){if(typeof value!=="string")return fallback;const [hour,minute]=value.split(":").map(Number);if(!Number.isFinite(hour))return fallback;const suffix=hour>=12?"p. m.":"a. m.";const display=hour%12||12;return `${display}:${String(minute||0).padStart(2,"0")} ${suffix}`}
const stockLabel=(value:unknown,fallback="Disponible")=>value==="out_of_stock"?"Agotado":value==="low_stock"?"Bajo inventario":fallback;

function mapProducts(rows:ProductRecord[]):Product[]{return rows.map((row,index)=>{const fallback=products.find(p=>p.slug===row.slug)||products.find(p=>row.name.toLowerCase().includes(p.name.toLowerCase()))||products[index%products.length];return {slug:row.slug||fallback.slug,name:text(row.name,fallback.name),category:text(row.category,fallback.category),maker:text(row.producer_name,fallback.maker),price:numeric(row.price,fallback.price),member:numeric(row.member_price,fallback.member),image:text(row.image_url,fallback.image),tag:row.is_coffee_of_month?"Café del mes":fallback.tag,stock:stockLabel(row.stock_status,fallback.stock),region:text(row.origin_region,fallback.region||""),process:fallback.process,notes:text(row.flavor_notes,fallback.notes||"")}})}
function mapProducers(rows:ProducerRecord[]):Producer[]{return rows.map((row,index)=>{const fallback=producers.find(p=>p.slug===row.slug)||producers.find(p=>p.name===row.name)||producers[index%producers.length];return {slug:row.slug||fallback.slug,name:text(row.name,fallback.name),region:text(row.region,fallback.region),story:text(row.story||row.description_short,fallback.story),image:text(row.image_url,fallback.image)}})}
function mapEvents(rows:EventRecord[]):Event[]{return rows.map((row,index)=>{const fallback=events.find(e=>e.slug===row.slug)||events.find(e=>e.name===row.name)||events[index%events.length];return {id:row.id||fallback.id,slug:row.slug||fallback.slug,name:text(row.name,fallback.name),type:text(row.event_type,fallback.type),date:eventDate(row.event_date||row.date,fallback.date),time:eventTime(row.start_time,fallback.time),price:row.is_free?0:numeric(row.price,fallback.price),member:row.is_free?0:numeric(row.member_price,fallback.member),seats:numeric(row.available_spots,fallback.seats),image:text(row.image_url,fallback.image),featured:fallback.featured}})}
function mapPlans(rows:MembershipRecord[]):Plan[]{return rows.map((row,index)=>{const fallback=plans.find(p=>p.name===row.name)||plans[index%plans.length];return {name:text(row.name,fallback.name),price:numeric(row.price_monthly??row.price,fallback.price),kicker:text(row.description,fallback.kicker),features:fallback.features,popular:row.featured??fallback.popular}})}

function go(path:string){ history.pushState({},"",path); dispatchEvent(new PopStateEvent("popstate")); scrollTo({top:0,behavior:"smooth"}); }
function Link({to,children,className=""}:{to:string;children:React.ReactNode;className?:string}){ return <a href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey){e.preventDefault();go(to)}}}>{children}</a> }
function Icon({children}:{children:string}){return <span className="icon" aria-hidden>{children}</span>}

function Header({logged,setLogged}:{logged:boolean;setLogged:(v:boolean)=>void}){
 const [open,setOpen]=useState(false);
 return <><div className="topline">Envíos en Bogotá · Recoge en nuestra sede · <b>Beneficios para miembros</b></div><header>
  <Link to="/" className="brand"><span className="brandmark">C</span><span>CLUB DEL CAFÉ<small>BOGOTÁ</small></span></Link>
  <button className="menu" onClick={()=>setOpen(!open)} aria-label="Abrir menú">☰</button>
  <nav className={open?"open":""} onClick={()=>setOpen(false)}><Link to="/marketplace">Marketplace</Link><Link to="/calendario">Calendario</Link><Link to="/productores">Productores</Link><Link to="/membresias">Membresías</Link><Link to="/sede">Sede</Link></nav>
  <div className="header-actions">{logged?<><Link to="/mi-club" className="login">Mi Club</Link><button className="join" onClick={()=>setLogged(false)}>Salir</button></>:<><Link to="/login" className="login">Ingresar</Link><Link to="/registro" className="join">Unirme</Link></>}</div>
 </header></>
}
function Footer(){return <footer><div><div className="brand light"><span className="brandmark">C</span><span>CLUB DEL CAFÉ<small>BOGOTÁ</small></span></div><p>Cada mes, un café. Cada café, una historia.<br/>Cada historia, una experiencia.</p></div><div><b>Explora</b><Link to="/marketplace">Marketplace</Link><Link to="/calendario">Calendario</Link><Link to="/productores">Productores</Link></div><div><b>Visítanos</b><span>Chapinero Alto, Bogotá</span><span>Lun–Sáb · 8 a. m.–8 p. m.</span><a href={whatsapp("Hola, quiero más información sobre Club del Café.")} target="_blank">WhatsApp ↗</a><a href="https://www.instagram.com/clubdelcafe__?igsh=MW9wZmNtbzY5OWx1Nw==" target="_blank" rel="noreferrer">Instagram ↗</a></div><div className="footer-note">Hecho con café colombiano.<br/>© 2026 Club del Café</div></footer>}
function WhatsApp({message,label="Escribir por WhatsApp",className="btn primary",onClick}:{message:string;label?:string;className?:string;onClick?:()=>void}){return <a className={className} href={whatsapp(message)} target="_blank" rel="noreferrer" onClick={onClick}><Icon>◉</Icon>{label}</a>}
function ProductCard({p}:{p:Product}){return <article className="product-card"><Link to={`/marketplace/${p.slug}`} className="card-image"><img src={p.image} alt={p.name}/>{p.tag&&<span className="tag">{p.tag}</span>}<span className="heart">♡</span></Link><div className="card-body"><small>{p.category}</small><Link to={`/marketplace/${p.slug}`}><h3>{p.name}</h3></Link><p>{p.maker}</p><div className="prices"><b>{money(p.price)}</b><span>Miembro {money(p.member)}</span></div><Link className="arrow-link" to={`/marketplace/${p.slug}`}>Ver producto <span>→</span></Link></div></article>}
function EventCard({e}:{e:Event}){return <article className="event-card"><div className="datebox"><b>{e.date.split(" ")[0]}</b><span>{e.date.split(" ")[1]}</span></div><Link to={`/calendario/${e.slug}`} className="event-img"><img src={e.image} alt={e.name}/></Link><div className="event-info"><small>{e.type} · {e.time}</small><Link to={`/calendario/${e.slug}`}><h3>{e.name}</h3></Link><p>{e.price?`${money(e.price)} · `:"Entrada libre · "}{e.seats} cupos</p></div><Link to={`/calendario/${e.slug}`} className="circle-arrow">↗</Link></article>}
function ProducerCard({p}:{p:Producer}){return <Link to={`/productores/${p.slug}`} className="producer-card"><img src={p.image} alt={p.name}/><div><small>{p.region}</small><h3>{p.name}</h3><p>{p.story}</p><span>Conocer su historia →</span></div></Link>}

function Home(){const {products,events,producers}=useClubData();return <>
 <section className="hero"><div className="hero-content"><p className="eyebrow">CAFÉ · COMUNIDAD · EXPERIENCIAS</p><h1>El café sabe mejor<br/><em>cuando se comparte.</em></h1><p>Descubre cafés de productores colombianos, vive experiencias y haz parte de una comunidad alrededor del ritual del café.</p><div className="hero-ctas"><Link to="/membresias" className="btn cream">Haz parte del Club</Link><Link to="/calendario" className="text-link">Ver próximas experiencias →</Link></div><div className="hero-stats"><span><b>12</b> productores aliados</span><span><b>+280</b> miembros</span><span><b>8</b> experiencias al mes</span></div></div><div className="hero-image"><img src={images.venue} alt="Barra de café del Club"/><div className="floating-note"><Icon>✦</Icon><span>Una sede real.<br/><b>Un club vivo.</b></span></div></div></section>
 <section className="manifest"><p className="eyebrow">MÁS QUE UNA CAFETERÍA</p><h2>Un lugar para encontrarnos<br/>alrededor de una buena taza.</h2><div className="manifest-grid"><p>Club del Café nace en Bogotá como un punto de encuentro entre personas curiosas, productores y nuevas formas de vivir el café colombiano.</p><p>Aquí puedes llevar el ritual a casa, conocer quién está detrás de cada grano y reservar experiencias que afinan los sentidos.</p><Link to="/sede" className="round-link">Conoce<br/>la sede <span>↗</span></Link></div></section>
 <section className="coffee-month"><div className="coffee-photo"><img src={images.huila} alt="Café del mes Huila Lavado"/><span className="vertical">CAFÉ DEL MES · AGOSTO</span></div><div className="coffee-copy"><p className="eyebrow">EDICIÓN 08 · HUILA</p><h2>Huila<br/><em>Lavado</em></h2><p>Una taza dulce y luminosa que cuenta la historia de una familia cafetera en las montañas de Pitalito.</p><div className="taste"><span><b>Notas</b>Panela · Mandarina · Cacao</span><span><b>Proceso</b>Lavado · 1.780 m s. n. m.</span></div><blockquote>“Cuidamos cada cereza como si fuera la única.”<cite>— Luz Marina, Finca El Horizonte</cite></blockquote><div><Link to="/marketplace/huila-lavado" className="btn primary">Descubrir este café</Link><span className="member-save">Miembros ahorran $8.000</span></div></div></section>
 <SectionTitle kicker="AGENDA DEL CLUB" title="Próximas experiencias" link="/calendario" />
 <div className="event-list">{events.slice(0,3).map(e=><EventCard key={e.slug} e={e}/>)}</div>
 <section className="dark-section"><SectionTitle kicker="CURADURÍA DEL CLUB" title="Lleva el ritual a casa" link="/marketplace" light/><div className="product-grid dark-grid">{products.slice(0,4).map(p=><ProductCard key={p.slug} p={p}/>)}</div></section>
 <section className="membership-tease"><div><p className="eyebrow">HAZ PARTE</p><h2>Tu café.<br/>Tu ritual.<br/><em>Tu Club.</em></h2></div><div><p>Ser miembro es descubrir algo nuevo cada mes y tener siempre una mesa reservada en nuestra comunidad.</p><ul><li>Precios especiales en café y métodos</li><li>Experiencias incluidas o anticipadas</li><li>Beneficios mensuales en nuestra sede</li></ul><Link to="/membresias" className="btn primary">Conocer membresías</Link></div><div className="member-card-visual"><span>CLUB DEL CAFÉ</span><b>CATADOR</b><small>MIEMBRO Nº 0284</small></div></section>
 <SectionTitle kicker="DETRÁS DE CADA TAZA" title="Productores aliados" link="/productores" />
 <div className="producer-grid">{producers.map(p=><ProducerCard key={p.slug} p={p}/>)}</div>
 <section className="venue"><img src={images.venue} alt="Sede Club del Café"/><div><p className="eyebrow">CHAPINERO · BOGOTÁ</p><h2>La sede es el<br/><em>corazón del Club.</em></h2><p>Una barra abierta para probar, aprender, conversar y volver. Ven por una taza; quédate por la comunidad.</p><Link to="/sede" className="btn cream">Visitar la sede</Link></div></section>
 </>}
function SectionTitle({kicker,title,link,light=false}:{kicker:string;title:string;link:string;light?:boolean}){return <div className={`section-title ${light?"light":""}`}><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><Link to={link}>Ver todo <span>→</span></Link></div>}

function Marketplace(){const {products}=useClubData();const [filter,setFilter]=useState("Todos");const cats=["Todos","Café del mes","Cafés colombianos","Métodos","Accesorios","Kits"];const shown=filter==="Todos"?products:products.filter(p=>p.category===filter);return <main><PageHero kicker="MARKETPLACE" title="El ritual, en tus manos." text="Cafés con origen, métodos y objetos que hacen de cada preparación un momento especial."/><div className="filters">{cats.map(c=><button className={filter===c?"active":""} key={c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="catalog-head"><p>{shown.length} productos</p><select aria-label="Ordenar"><option>Curaduría del Club</option><option>Menor precio</option><option>Mayor precio</option></select></div><div className="product-grid catalog">{shown.map(p=><ProductCard key={p.slug} p={p}/>)}</div></main>}
function ProductDetail({slug}:{slug:string}){const {products}=useClubData();const p=products.find(x=>x.slug===slug)||products[0];return <main><div className="breadcrumbs"><Link to="/marketplace">Marketplace</Link> / {p.category} / <b>{p.name}</b></div><section className="detail"><div className="detail-image"><img src={p.image} alt={p.name}/>{p.tag&&<span className="tag">{p.tag}</span>}</div><div className="detail-copy"><p className="eyebrow">{p.category} · {p.maker}</p><h1>{p.name}</h1><p className="lead">Una selección del Club para disfrutar un café colombiano transparente, dulce y memorable.</p><div className="detail-price"><b>{money(p.price)}</b><span>Precio miembro <strong>{money(p.member)}</strong></span></div><div className="availability">● {p.stock}</div>{p.region&&<div className="specs"><span><b>Región</b>{p.region}</span><span><b>Proceso</b>{p.process}</span><span><b>Notas</b>{p.notes}</span><span><b>Tueste</b>Medio</span></div>}<WhatsApp message={`Hola, quiero comprar este producto del Club del Café: ${p.name}.`} label="Comprar por WhatsApp"/><p className="micro">Coordinamos pago y entrega personalmente por WhatsApp.</p></div></section><section className="story"><p className="eyebrow">LA HISTORIA EN LA TAZA</p><h2>Un café que habla<br/>de su territorio.</h2><p>{p.region?`Cultivado en ${p.region}, este lote fue seleccionado por su carácter limpio y su dulzor natural. Trabajamos directamente con ${p.maker} para que cada compra reconozca el trabajo detrás del grano.`:"Elegimos objetos durables, honestos y fáciles de integrar al ritual diario. Una pieza pensada para acompañar muchas mañanas."}</p></section><SectionTitle kicker="TAMBIÉN TE PUEDE GUSTAR" title="Sigue explorando" link="/marketplace"/><div className="product-grid related">{products.filter(x=>x.slug!==p.slug).slice(0,3).map(x=><ProductCard key={x.slug} p={x}/>)}</div></main>}
function Calendar(){const {events}=useClubData();const [filter,setFilter]=useState("Todos");const types=["Todos","Cata","Taller","Maridaje","Charla","Gratuito"];const shown=filter==="Todos"?events:events.filter(e=>e.type===filter);return <main><PageHero kicker="AGENDA DEL CLUB" title="Experiencias para afinar los sentidos." text="Catas, talleres y conversaciones para descubrir todo lo que puede pasar alrededor de una taza."/><div className="filters">{types.map(t=><button className={filter===t?"active":""} onClick={()=>setFilter(t)} key={t}>{t}</button>)}</div><div className="calendar-layout"><aside><b>AGOSTO — SEPTIEMBRE</b><p>Todos los eventos suceden en nuestra sede de Chapinero, salvo indicación.</p><WhatsApp message="Hola, quiero más información sobre las actividades de Club del Café." label="¿Tienes preguntas?" className="text-link"/></aside><div className="event-list full">{shown.map(e=><EventCard key={e.slug} e={e}/>)}</div></div></main>}
function EventDetail({slug}:{slug:string}){const {events}=useClubData();const e=events.find(x=>x.slug===slug)||events[0];const [guestName,setGuestName]=useState("");const [guestPhone,setGuestPhone]=useState("");const [guestEmail,setGuestEmail]=useState("");const [numberOfSpots,setNumberOfSpots]=useState(1);function reserve(event:FormEvent<HTMLFormElement>){event.preventDefault();const message=`Hola, soy ${guestName}. Quiero reservar ${numberOfSpots} cupo${numberOfSpots===1?"":"s"} para ${e.name} el día ${e.date}.`;window.open(whatsapp(message),"_blank","noopener,noreferrer");void createEventReservation({eventId:e.id,guestName,guestPhone,guestEmail:guestEmail||null,numberOfSpots,totalPrice:e.price*numberOfSpots,paymentStatus:e.price===0?"not_required":"pending",notes:"Reserva iniciada desde WhatsApp."});}return <main><div className="event-hero"><img src={e.image} alt={e.name}/><div><p className="eyebrow">{e.type} · EXPERIENCIA DEL CLUB</p><h1>{e.name}</h1><p>Una experiencia guiada para probar, conversar y entender el café colombiano desde una mirada nueva.</p></div></div><div className="event-detail"><div><p className="eyebrow">SOBRE LA EXPERIENCIA</p><h2>Una conversación<br/>que empieza en la taza.</h2><p>Recorreremos aromas, sabores y decisiones de origen de manera cercana. No necesitas experiencia previa: solo curiosidad y ganas de compartir.</p><h3>¿Qué incluye?</h3><ul><li>Degustación guiada de cafés seleccionados</li><li>Material de apoyo y receta para casa</li><li>Conversación con nuestro equipo de barra</li></ul></div><aside><span>FECHA <b>{e.date}</b></span><span>HORA <b>{e.time}</b></span><span>DURACIÓN <b>2 horas</b></span><span>LUGAR <b>Sede Chapinero</b></span><span>CUPOS <b>{e.seats} disponibles</b></span><div className="detail-price"><b>{e.price?money(e.price):"Entrada libre"}</b><span>Miembro <strong>{e.member?money(e.member):"Incluido"}</strong></span></div><form onSubmit={reserve}><label>Nombre<input required value={guestName} onChange={event=>setGuestName(event.target.value)} autoComplete="name"/></label><label>Celular<input required type="tel" value={guestPhone} onChange={event=>setGuestPhone(event.target.value)} autoComplete="tel"/></label><label>Correo electrónico (opcional)<input type="email" value={guestEmail} onChange={event=>setGuestEmail(event.target.value)} autoComplete="email"/></label><label>Número de cupos<input required type="number" min="1" value={numberOfSpots} onChange={event=>setNumberOfSpots(Math.max(1,Number(event.target.value)||1))}/></label><button className="btn primary" type="submit"><Icon>◉</Icon>Reservar por WhatsApp</button></form></aside></div></main>}
function Producers(){const {producers}=useClubData();return <main><PageHero kicker="NUESTROS ALIADOS" title="Personas detrás de cada taza." text="Conoce las fincas, tostadores y proyectos que dan origen a los cafés del Club."/><div className="producer-grid producer-page">{producers.map(p=><ProducerCard key={p.slug} p={p}/>)}</div></main>}
function ProducerDetail({slug}:{slug:string}){const {producers,products}=useClubData();const p=producers.find(x=>x.slug===slug)||producers[0];return <main><section className="producer-detail"><img src={p.image} alt={p.name}/><div><p className="eyebrow">{p.region} · PRODUCTOR ALIADO</p><h1>{p.name}</h1><p className="lead">{p.story}</p><p>Su trabajo combina conocimiento heredado, cuidado del territorio y una búsqueda constante por expresar la identidad de cada cosecha.</p><Link to="/marketplace" className="btn primary">Ver sus cafés</Link></div></section><SectionTitle kicker="DISPONIBLES EN EL CLUB" title="Cafés de este productor" link="/marketplace"/><div className="product-grid related">{products.filter(x=>x.maker===p.name).concat(products).slice(0,3).map((x,i)=><ProductCard key={x.slug+i} p={x}/>)}</div></main>}
function Memberships(){const {plans}=useClubData();return <main><PageHero kicker="MEMBRESÍAS" title="Hay un lugar para ti en el Club." text="Elige cómo quieres vivir el café: a tu ritmo, una bolsa cada mes o con la experiencia completa."/><div className="plans">{plans.map(p=><article className={p.popular?"popular":""} key={p.name}>{p.popular&&<span className="tag">MÁS ELEGIDO</span>}<p className="eyebrow">PLAN</p><h2>{p.name}</h2><p>{p.kicker}</p><div className="plan-price"><b>{money(p.price)}</b><span>/ mes</span></div><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><WhatsApp message={`Hola, quiero unirme al Club del Café con la membresía ${p.name}.`} label={`Elegir ${p.name}`} className={p.popular?"btn cream":"btn outline"}/></article>)}</div><section className="compare"><p className="eyebrow">EN TODOS LOS PLANES</p><h2>Más café. Más historias.<br/>Más comunidad.</h2><div><span>Precios de miembro</span><span>Acceso anticipado</span><span>Contenido del café del mes</span><span>Comunidad y sede</span></div></section><section className="faq"><h2>Preguntas frecuentes</h2>{["¿Puedo cambiar de plan?","¿Cómo recibo mi café mensual?","¿Las membresías tienen permanencia?","¿Cómo activo mis beneficios?"].map(q=><details key={q}><summary>{q}<span>+</span></summary><p>Nuestro equipo te acompaña personalmente por WhatsApp. La membresía es flexible y se activa una vez confirmemos contigo los detalles.</p></details>)}</section></main>}
function Venue(){const {events}=useClubData();return <main><section className="venue-page"><div><p className="eyebrow">CHAPINERO ALTO · BOGOTÁ</p><h1>La sede es el<br/><em>corazón del Club.</em></h1><p>Un lugar para tomar café sin prisa, conocer nuevas historias y encontrarnos alrededor de una mesa.</p><div className="venue-data"><span><b>Dirección</b>Av. Carrera 19 # 95 - 55, Bogotá, Colombia</span><span><b>Horario</b>Lun–Sáb · 8 a. m.–8 p. m.<br/>Dom · 9 a. m.–5 p. m.</span><span><b>Contacto</b>+57 300 123 4567</span></div><a className="btn primary" href="https://maps.google.com/?q=Av.+Carrera+19+95-55+Bogota+Colombia" target="_blank">Cómo llegar ↗</a></div><img src={images.venue} alt="Interior de la sede"/></section><SectionTitle kicker="ESTA SEMANA EN LA SEDE" title="Ven a vivir el Club" link="/calendario"/><div className="event-list">{events.slice(0,3).map(e=><EventCard key={e.slug} e={e}/>)}</div></main>}
function PageHero({kicker,title,text}:{kicker:string;title:string;text:string}){return <section className="page-hero"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{text}</p></section>}

function Auth({kind,setLogged}:{kind:"login"|"register";setLogged:(v:boolean)=>void}){function submit(e:FormEvent){e.preventDefault();setLogged(true);go("/mi-club")}return <main className="auth-page"><div className="auth-photo"><img src={images.event2} alt="Café preparado en el Club"/><blockquote>“Cada mes, un café.<br/>Cada café, una historia.”</blockquote></div><form className="auth-form" onSubmit={submit}><p className="eyebrow">{kind==="login"?"BIENVENIDO DE VUELTA":"HAZ PARTE DEL CLUB"}</p><h1>{kind==="login"?"Tu mesa está lista.":"Empecemos por conocerte."}</h1><p>{kind==="login"?"Ingresa para ver tus beneficios y próximas experiencias.":"Crea tu cuenta y descubre una nueva forma de vivir el café."}</p>{kind==="register"&&<div className="two"><label>Nombre<input required placeholder="Tu nombre" autoComplete="given-name"/></label><label>Apellido<input required placeholder="Tu apellido" autoComplete="family-name"/></label></div>}<label>Correo electrónico<input type="email" required placeholder="hola@ejemplo.com" autoComplete="email"/></label>{kind==="register"&&<label>Celular<input type="tel" required placeholder="300 000 0000" autoComplete="tel"/></label>}<label>Contraseña<input type="password" required placeholder="••••••••" autoComplete={kind==="register"?"new-password":"current-password"}/></label>{kind==="register"&&<label className="check"><input type="checkbox" required/> Acepto términos y tratamiento de datos.</label>}<button className="btn primary" type="submit">{kind==="login"?"Ingresar a Mi Club":"Crear mi cuenta"}</button><p className="switch">{kind==="login"?<>¿Aún no haces parte? <Link to="/registro">Crea tu cuenta</Link></>:<>¿Ya tienes cuenta? <Link to="/login">Ingresa aquí</Link></>}</p></form></main>}
function Member({sub="home",setLogged}:{sub?:string;setLogged:(v:boolean)=>void}){const nav=[['','Resumen'],['beneficios','Beneficios'],['reservas','Reservas'],['cafe-del-mes','Café del mes'],['perfil','Perfil']];return <main className="portal"><aside><Link to="/" className="brand light"><span className="brandmark">C</span><span>CLUB DEL CAFÉ<small>MI CLUB</small></span></Link><nav>{nav.map(([s,n])=><Link key={s} to={`/mi-club${s?`/${s}`:""}`} className={sub===(s||"home")?"active":""}>{n}</Link>)}</nav><button onClick={()=>{setLogged(false);go("/")}}>Cerrar sesión</button></aside><div className="portal-content">{sub==="home"?<MemberHome/>:sub==="beneficios"?<Benefits/>:sub==="reservas"?<Reservations/>:sub==="cafe-del-mes"?<MonthCoffee/>:<Profile/>}</div></main>}
function MemberHome(){return <><p className="eyebrow">MI CLUB</p><h1>Hola, Ana.<br/><em>Bienvenida a tu Club.</em></h1><div className="member-summary"><div><small>PLAN ACTUAL</small><b>Catador</b><span className="status">● Activa</span></div><div><small>PRÓXIMA RENOVACIÓN</small><b>28 de agosto</b><Link to="/membresias">Ver membresía →</Link></div></div><h2>Tus beneficios de agosto</h2><div className="benefit-grid"><div><Icon>☕</Icon><b>1 bebida</b><span>Disponible en sede</span></div><div><Icon>◒</Icon><b>Café mensual</b><span>Listo para recoger</span></div><div><Icon>✦</Icon><b>Cata grupal</b><span>Incluida este mes</span></div></div><h2>Tu próxima experiencia</h2><EventCard e={events[0]}/></>}
function Benefits(){return <><p className="eyebrow">PLAN CATADOR</p><h1>Tus beneficios</h1><p className="lead">Todo lo que tienes disponible este mes, en un solo lugar.</p><div className="benefit-list">{[['Bebida del mes','1 disponible','Disponible'],['Bolsa Huila Lavado','Lista para recoger','Disponible'],['Cata grupal','22 de agosto','Reservado'],['Descuento marketplace','Hasta 15%','Siempre activo']].map(x=><div key={x[0]}><Icon>✦</Icon><span><b>{x[0]}</b>{x[1]}</span><em>{x[2]}</em></div>)}</div></>}
function Reservations(){return <><p className="eyebrow">MI AGENDA</p><h1>Mis reservas</h1><div className="reservation"><img src={events[0].image} alt="Cata"/><div><small>CONFIRMADA</small><h2>{events[0].name}</h2><p>22 de agosto · 5:30 p. m. · 1 cupo</p><Link to={`/calendario/${events[0].slug}`}>Ver evento →</Link></div></div></>}
function MonthCoffee(){return <><p className="eyebrow">AGOSTO · EDICIÓN 08</p><h1>Huila <em>Lavado</em></h1><div className="month-layout"><img src={images.huila} alt="Huila lavado"/><div><h2>Una historia de altura y paciencia.</h2><p>Desde Pitalito llega una taza luminosa de Luz Marina y su familia. Panela, mandarina y cacao en un café hecho para las mañanas sin prisa.</p><div className="specs"><span><b>Región</b>Pitalito, Huila</span><span><b>Receta</b>V60 · 15 g / 250 ml</span></div><Link to="/marketplace/huila-lavado" className="btn primary">Comprar otra bolsa</Link></div></div></>}
function Profile(){return <><p className="eyebrow">TU INFORMACIÓN</p><h1>Perfil</h1><form className="profile-form"><div className="two"><label>Nombre<input defaultValue="Ana"/></label><label>Apellido<input defaultValue="Gómez"/></label></div><label>Correo<input defaultValue="ana@ejemplo.com"/></label><label>Celular<input defaultValue="300 555 0101"/></label><label>Preferencia de café<select><option>Balanceado y dulce</option><option>Frutal y brillante</option></select></label><button className="btn primary">Guardar cambios</button></form></>}

function Admin({sub="home"}:{sub?:string}){const [items,setItems]=useState(products);const names:{[k:string]:string}={home:"Dashboard",productos:"Productos",eventos:"Eventos",productores:"Productores",miembros:"Miembros",reservas:"Reservas",pedidos:"Pedidos",configuracion:"Configuración"};return <main className="portal admin"><aside><Link to="/" className="brand light"><span className="brandmark">C</span><span>CLUB DEL CAFÉ<small>ADMIN</small></span></Link><nav>{Object.entries(names).map(([s,n])=><Link key={s} to={`/admin${s==='home'?'':`/${s}`}`} className={sub===s?"active":""}>{n}</Link>)}</nav><Link to="/">Volver al sitio</Link></aside><div className="portal-content"><p className="eyebrow">ADMINISTRACIÓN</p><div className="admin-head"><h1>{names[sub]||"Dashboard"}</h1>{sub!=="home"&&<button className="btn primary" onClick={()=>sub==="productos"&&setItems([{...products[0],slug:`nuevo-${items.length}`,name:"Nuevo producto",tag:"Borrador"},...items])}>+ Crear nuevo</button>}</div>{sub==="home"?<Dashboard/>:<AdminTable type={sub} items={items} setItems={setItems}/>}</div></main>}
function Dashboard(){return <><p className="lead">Buenos días. Esto está pasando hoy en el Club.</p><div className="stats"><div><small>MIEMBROS ACTIVOS</small><b>284</b><span>+12 este mes</span></div><div><small>EVENTOS PRÓXIMOS</small><b>5</b><span>54 reservas</span></div><div><small>RESERVAS PENDIENTES</small><b>7</b><span>Requieren atención</span></div><div><small>PEDIDOS ABIERTOS</small><b>12</b><span>4 listos</span></div></div><div className="admin-grid"><section><h2>Próximos eventos</h2>{events.slice(0,3).map(e=><div className="mini-row" key={e.slug}><span className="mini-date">{e.date}</span><b>{e.name}</b><small>{e.seats} cupos</small></div>)}</section><section><h2>Acciones rápidas</h2><div className="quick"><Link to="/admin/productos">+ Producto</Link><Link to="/admin/eventos">+ Evento</Link><Link to="/admin/productores">+ Productor</Link><Link to="/admin/miembros">Ver miembros</Link></div></section></div></>}
function AdminTable({type,items,setItems}:{type:string;items:Product[];setItems:(p:Product[])=>void}){const data=type==="productos"?items:type==="eventos"?events:type==="productores"?producers:type==="miembros"?[{name:"Ana Gómez",category:"Catador",maker:"Activa"},{name:"Carlos Ruiz",category:"Explorador",maker:"Activa"},{name:"Laura Díaz",category:"Ritual",maker:"Pendiente"}]:type==="reservas"?events.slice(0,4).map(e=>({name:e.name,category:e.date,maker:"Confirmada"})):type==="pedidos"?products.slice(0,4).map(p=>({name:p.name,category:"Solicitud WhatsApp",maker:"Pendiente"})):[{name:"Número de WhatsApp",category:"Contacto",maker:"+57 300 123 4567"}];return <div className="admin-table"><div className="table-tools"><input placeholder="Buscar…"/><select><option>Todos los estados</option></select></div>{data.map((x:any,i:number)=><div className="table-row" key={(x.slug||x.name)+i}>{x.image?<img src={x.image} alt=""/>:<span className="avatar">{x.name[0]}</span>}<span><b>{x.name}</b><small>{x.category||x.region}</small></span><span className="status">● {x.stock||x.maker||"Activo"}</span><button onClick={()=>type==="productos"&&setItems(items.filter(p=>p.slug!==x.slug))}>•••</button></div>)}</div>}

export default function ClubApp(){const [path,setPath]=useState("/");const [logged,setLogged]=useState(false);const [clubData,setClubData]=useState<ClubData>({products,events,producers,plans});useEffect(()=>{const sync=()=>setPath(location.pathname);sync();addEventListener("popstate",sync);return()=>removeEventListener("popstate",sync)},[]);useEffect(()=>{let active=true;Promise.all([getProducts(),getEvents(),getProducers(),getMemberships()]).then(([productRows,eventRows,producerRows,membershipRows])=>{if(active)setClubData({products:mapProducts(productRows),events:mapEvents(eventRows),producers:mapProducers(producerRows),plans:mapPlans(membershipRows)})}).catch(error=>console.warn("[Club del Café] No fue posible actualizar los datos; continúan activos los mocks.",error));return()=>{active=false}},[]);const parts=useMemo(()=>path.split("/").filter(Boolean),[path]);let content:React.ReactNode;if(path==="/")content=<Home/>;else if(parts[0]==="marketplace")content=parts[1]?<ProductDetail slug={parts[1]}/>:<Marketplace/>;else if(parts[0]==="calendario")content=parts[1]?<EventDetail slug={parts[1]}/>:<Calendar/>;else if(parts[0]==="productores")content=parts[1]?<ProducerDetail slug={parts[1]}/>:<Producers/>;else if(path==="/membresias")content=<Memberships/>;else if(path==="/sede")content=<Venue/>;else if(path==="/login")content=<Auth kind="login" setLogged={setLogged}/>;else if(path==="/registro")content=<Auth kind="register" setLogged={setLogged}/>;else if(parts[0]==="mi-club")content=<Member sub={parts[1]||"home"} setLogged={setLogged}/>;else if(parts[0]==="admin")content=<Admin sub={parts[1]||"home"}/>;else content=<Home/>;const portal=parts[0]==="mi-club"||parts[0]==="admin";return <ClubDataContext.Provider value={clubData}><>{!portal&&<Header logged={logged} setLogged={setLogged}/>} {content} {!portal&&<Footer/>}<a className="wa-float" href={whatsapp("Hola, quiero más información sobre Club del Café.")} target="_blank" aria-label="WhatsApp">◉</a></></ClubDataContext.Provider>}
